# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-25 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=10, verbose_name='Symbol of currency'),
        ),
    ]
