# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-06 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_auto_20171225_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencydata',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_data', to='currencies.Currency'),
        ),
    ]
