# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-06 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_auto_20180106_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencydata',
            name='last_updated',
            field=models.PositiveIntegerField(),
        ),
    ]
