# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-06 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_auto_20180106_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencydata',
            name='max_supply',
            field=models.FloatField(null=True),
        ),
    ]
