# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-06 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_auto_20180106_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=10, null=True, verbose_name='Symbol of currency'),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='available_supply',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_data', to='currencies.Currency'),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='daily_volume_usd',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='last_updated',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='market_cap_usd',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='percent_change_1h',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='percent_change_24h',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='percent_change_7d',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='price_btc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='price_usd',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='rank',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='total_supply',
            field=models.FloatField(null=True),
        ),
    ]
